import * as images from './images';

export const lists = [
    {
        id:1,
        image: images?.smartphone,
        content: 'Canon Cmera EOS 2000, Black 10x zoom',
        price: '$998.00',
        oldprice: '$1128.00',
        stars: images?.star,
        number: '7.5',
        dot: images?.dot,
        order: '154 order',
        dots: images?.dot2,
        text1: 'Free shipping',
        text2: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmodtempor incididunt ut labore et dolore magna aliqua',
        link: 'View details',
        wishlist: images?.fav1,
        favorite: images?.favorite,
        addtocart: false,
    },
    {
        id:2,
        image: images?.mob1,
        content: 'GoPro HERO6 4K Action Camera - Black',
        price: '$998.00',
        stars: images?.star,
        number: '7.5',
        dot: images?.dot,
        order: '154 order',
        dots: images?.dot2,
        text1: 'Free shipping',
        text2: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit',
        link: 'View details',
        wishlist: images?.fav1,
        favorite: images?.favorite,
        addtocart: false,
    },
    {
        id:3,
        image: images?.mobile,
        content: 'GoPro HERO6 4K Action Camera - Black',
        price: '$998.00',
        stars: images?.star,
        number: '7.5',
        dot: images?.dot,
        order: '154 order',
        dots: images?.dot2,
        text1:'Free shipping',
        text2: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit',
        link: 'View details',
        wishlist: images?.fav1,
        favorite: images?.favorite,
        addtocart: false,
    },
    {
        id:4,
        image: images?.laptop,
        content: 'GoPro HERO6 4K Action Camera - Black',
        price: '$998.00',
        stars: images?.star,
        number: '7.5',
        dot: images?.dot,
        order: '154 order',
        dots: images?.dot2,
        text1: 'Free shipping',
        text2: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit',
        link: 'View details',
        wishlist: images?.fav1,
        favorite: images?.favorite,
        addtocart: false,
    },
    {
        id:5,
        image: images?.watch,
        content: 'GoPro HERO6 4K Action Camera - Black',
        price: '$998.00',
        oldprice: '$1128.00',
        stars: images?.star,
        number: '7.5',
        dot: images?.dot,
        order: '154 order',
        dots: images?.dot2,
        text1: 'Free shipping',
        text2: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit',
        link: 'View details',
        wishlist: images?.fav1,
        favorite: images?.favorite,
        addtocart: false,

    },
    {
        id:6,
        image: images?.headset,
        content: 'GoPro HERO6 4K Action Camera - Black',
        price: '$998.00',
        stars: images?.star,
        number: '7.5',
        dot: images?.dot,
        order: '154 order',
        dots: images?.dot2,
        text1: 'Free shipping',
        text2: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit',
        link: 'View details',
        wishlist: images?.fav1,
        favorite: images?.favorite,
        addtocart: false,
    },

]